### ISSUE TITLE
UnicodeEncodeError when logging

### ISSUE THREAD

**Issue by ulisdd** [collective/Products.feedfeeder#11]
Hi,

I got the following error when updating a feed. I think it's not the same problem like mentioned in the issues before, because this error occurs because of logging. An encode("utf-8") may help?

Kind regards,
Uli

Plone 4.3.4.1 (4309)
Feedfeeder: 2.7

Traceback (innermost last):  
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.feedfeeder.browser.feed, line 51, in __call__
  Module Products.feedfeeder.browser.feed, line 48, in update
  Module Products.feedfeeder.utilities, line 96, in retrieveFeedItems
  Module Products.feedfeeder.utilities, line 159, in _retrieveSingleFeed
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 2:
ordinal not in range(128)

**Comment by miohtama** [comment]
Can you try to make encode("utf-8") fix on your installation and see if it solves the problem? Seems like trivial fix.

**Comment by ulisdd** [comment]
I tried and it worked.

**Comment by miohtama** [comment]
Cool! Can you make a pull request for the fix. I think you should just be able to hit Edit button on Github web view for such small fix.

**Comment by mauritsvanrees** [comment]
Closing this old issue. The fix by @ulisdd was released last year in 2.8.
