### ISSUE TITLE
Cron jobs and clock server update URL

### ISSUE THREAD

**Issue by spanish** [collective/Products.feedfeeder#13]
Hi,

Now, cron jobs and clock server needs "?_authenticator=..." in order to work.

Sample:
feed-mega-update doesn't works
feed-mega-update?_authenticator=... works!

Regards,

Manuel

**Comment by mauritsvanrees** [comment]
Thanks for the report. I have released 3.0.0 with a fix.
Supported Plone released: 4.3 and 5.0.
